# Generated by Django 4.1.7 on 2023-03-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=25, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("item_group", models.CharField(max_length=25)),
                ("progress_order", models.IntegerField()),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("ITEM", "item"),
                            ("MASK", "mask"),
                            ("SONG", "song"),
                            ("EQUIPMENT", "equipment"),
                            ("REMAINS", "remains"),
                        ],
                        max_length=10,
                    ),
                ),
                ("quantity", models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                "verbose_name": "item",
                "verbose_name_plural": "items",
                "db_table": "items",
            },
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("item_group", "progress_order"), name="unique_group_progress"
            ),
        ),
    ]
